// src/ui/src/pages/Dashboard.tsx
import React, { useEffect, useState } from 'react';
import { Plus, Trash2, Settings, Power, Activity } from 'lucide-react';
import { useNavigate } from 'react-router-dom';
import WhatsAppManager from '../components/WhatsAppManager';
import TokenManager from '../components/TokenManager';
import UserManager from '../components/UserManager';

interface Account {
    id: number;
    name: string;
    status: 'stopped' | 'running';
    config: string;
}

const Dashboard = () => {
    const [accounts, setAccounts] = useState<Account[]>([]);
    const [newAccountName, setNewAccountName] = useState('');
    const navigate = useNavigate();

    const fetchAccounts = async () => {
        try {
            const res = await fetch('/api/accounts', {
                headers: { 'Authorization': `Bearer ${localStorage.getItem('token')}` }
            });
            if (res.status === 401) navigate('/login');
            const data = await res.json();
            setAccounts(data.accounts || []);
        } catch (e) { console.error(e); }
    };

    useEffect(() => { fetchAccounts(); }, []);

    const handleAddAccount = async (e: React.FormEvent) => {
        e.preventDefault();
        try {
            await fetch('/api/accounts', {
                method: 'POST',
                headers: {
                    'Content-Type': 'application/json',
                    'Authorization': `Bearer ${localStorage.getItem('token')}`
                },
                body: JSON.stringify({ name: newAccountName, config: '{}' })
            });
            // Close modal using checkbox hack or dialog method if using native dialog
            // DaisyUI recommends input toggle or dialog
            (document.getElementById('modal_add_account') as HTMLDialogElement).close();
            setNewAccountName('');
            fetchAccounts();
        } catch (e) {
            console.error(e);
        }
    };

    const handleDelete = async (id: number) => {
        if (!confirm('Are you sure?')) return;
        await fetch(`/api/accounts/${id}`, {
            method: 'DELETE',
            headers: { 'Authorization': `Bearer ${localStorage.getItem('token')}` }
        });
        fetchAccounts();
    };

    return (
        <div className="space-y-8 fade-in">
            {/* Header / Stats Section (Placeholder for future stats) */}
            <div className="flex justify-between items-end">
                <div>
                    <h2 className="text-3xl font-bold">Dashboard</h2>
                    <p className="opacity-70">Manage your WhatsApp Instances</p>
                </div>
                {/* <div className="stats shadow">
                  <div className="stat">
                    <div className="stat-title">Total Accounts</div>
                    <div className="stat-value">{accounts.length}</div>
                  </div>
                </div> */}
            </div>

            {/* Grid of Accounts */}
            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
                {/* Add New Card */}
                <div
                    onClick={() => (document.getElementById('modal_add_account') as HTMLDialogElement).showModal()}
                    className="card bg-base-100 shadow-xl border-2 border-dashed border-base-300 hover:border-primary cursor-pointer transition-colors h-full min-h-[300px] flex items-center justify-center group"
                >
                    <div className="flex flex-col items-center gap-2 group-hover:text-primary transition-colors">
                        <div className="p-4 bg-base-200 rounded-full group-hover:bg-primary/10">
                            <Plus size={32} />
                        </div>
                        <span className="font-semibold">Add New Instance</span>
                    </div>
                </div>

                {accounts.map(acc => (
                    <div key={acc.id} className="card bg-base-100 shadow-xl">
                        <div className="card-body p-6">
                            <div className="flex justify-between items-start mb-4">
                                <div>
                                    <h3 className="card-title text-xl">{acc.name}</h3>
                                    <div className="badge badge-sm mt-1 opacity-70">ID: {acc.id}</div>
                                </div>
                                <div className={`badge ${acc.status === 'running' ? 'badge-success gap-2' : 'badge-ghost gap-2'}`}>
                                    {acc.status === 'running' ? <Activity size={12} /> : <Power size={12} />}
                                    {acc.status}
                                </div>
                            </div>

                            {/* Instance Manager Component Logic would go here or be passed down */}
                            <div className="flex-grow">
                                <WhatsAppManager accountId={acc.id} />
                            </div>

                            <div className="card-actions justify-end mt-4 pt-4 border-t border-base-200">
                                <button className="btn btn-sm btn-ghost btn-square" title="Settings">
                                    <Settings size={18} />
                                </button>
                                <button onClick={() => handleDelete(acc.id)} className="btn btn-sm btn-ghost btn-square text-error" title="Delete">
                                    <Trash2 size={18} />
                                </button>
                            </div>
                        </div>
                    </div>
                ))}
            </div>

            <div className="divider"></div>

            {/* Token & User Management Sections using Tabs or just vertical Layout? Vertical for now. */}
            <div className="grid grid-cols-1 lg:grid-cols-2 gap-8">
                <div className="col-span-1">
                    <TokenManager />
                </div>
                <div className="col-span-1">
                    <UserManager />
                </div>
            </div>

            {/* Modal */}
            <dialog id="modal_add_account" className="modal">
                <div className="modal-box">
                    <h3 className="font-bold text-lg">Add New Instance</h3>
                    <form onSubmit={handleAddAccount} className="py-4">
                        <div className="form-control w-full">
                            <label className="label">
                                <span className="label-text">Instance Name</span>
                            </label>
                            <input
                                type="text"
                                placeholder="e.g. Sales Bot"
                                className="input input-bordered w-full"
                                value={newAccountName}
                                onChange={e => setNewAccountName(e.target.value)}
                                autoFocus
                            />
                        </div>
                        <div className="modal-action">
                            <form method="dialog">
                                {/* if there is a button in form, it will close the modal */}
                                <button className="btn btn-ghost mr-2">Cancel</button>
                            </form>
                            <button className="btn btn-primary" onClick={handleAddAccount}>Create</button>
                        </div>
                    </form>
                </div>
                <form method="dialog" className="modal-backdrop">
                    <button>close</button>
                </form>
            </dialog>
        </div>
    );
};

export default Dashboard;

// src/ui/src/pages/Dashboard.vue
<script setup lang="ts">
import { ref, onMounted } from 'vue';
import QRCode from 'qrcode';

interface Instance {
    id: number;
    name: string;
    status: string;
    qr: string | null;
    user?: { id: string; name: string };
}

const instances = ref<Instance[]>([]);
const loading = ref(false);
const qrDialog = ref(false);
const selectedQr = ref('');
const selectedName = ref('');

// Fetch Data
const fetchStatus = async () => {
    loading.value = true;
    try {
        const res = await fetch('/backend/wa/status', {
            headers: { 'Authorization': `Bearer ${localStorage.getItem('token')}` }
        });
        if (res.ok) {
            const data = await res.json();
            instances.value = data.instances;
        }
    } catch (e) {
        console.error(e);
    }
    loading.value = false;
};



const createDialog = ref(false);
const newInstanceName = ref('');

const createInstance = async () => {
    if (!newInstanceName.value) return;
    try {
        const res = await fetch('/backend/instances', {
            method: 'POST',
            headers: { 
                'Content-Type': 'application/json',
                'Authorization': `Bearer ${localStorage.getItem('token')}` 
            },
            body: JSON.stringify({ name: newInstanceName.value })
        });
        if (res.ok) {
            createDialog.value = false;
            newInstanceName.value = '';
            fetchStatus();
        }
    } catch(e) { console.error(e); }
};

const deleteInstance = async (id: number) => {
    if(!confirm('Delete this instance permanently?')) return;
    await fetch(`/backend/instances/${id}`, {
        method: 'DELETE',
        headers: { 'Authorization': `Bearer ${localStorage.getItem('token')}` }
    });
    fetchStatus();
};

// Actions
const startInstance = async (id: number) => {
    await fetch(`/backend/wa/start/${id}`, {
        method: 'POST',
        headers: { 'Authorization': `Bearer ${localStorage.getItem('token')}` }
    });
    fetchStatus(); // Poll update
};

const stopInstance = async (id: number) => {
     await fetch(`/backend/wa/logout/${id}`, {
        method: 'POST',
        headers: { 'Authorization': `Bearer ${localStorage.getItem('token')}` }
    });
    fetchStatus();
};

const showQr = async (qr: string, name: string) => {
    if (!qr) return;
    try {
        selectedQr.value = await QRCode.toDataURL(qr);
        selectedName.value = name;
        qrDialog.value = true;
    } catch (e) {
        console.error(e);
    }
};

onMounted(() => {
    fetchStatus();
    // Poll every 5s
    const timer = setInterval(fetchStatus, 5000);
    return () => clearInterval(timer);
});

const getStatusColor = (status: string) => {
    switch(status) {
        case 'connected': return 'success';
        case 'connecting': return 'warning';
        default: return 'error';
    }
}
</script>

<template>
  <v-container>
    <div class="d-flex align-center mb-6">
        <h1 class="text-h4 font-weight-bold">Dashboard</h1>
        <v-spacer></v-spacer>
        <v-btn color="primary" class="mr-2" prepend-icon="mdi-plus" @click="createDialog = true">Add Instance</v-btn>
        <v-btn prepend-icon="mdi-refresh" @click="fetchStatus" :loading="loading">Refresh</v-btn>
    </div>

    <v-row>
        <v-col v-for="inst in instances" :key="inst.id" cols="12" md="6" lg="4">
            <v-card class="glass-card h-100 pa-2 d-flex flex-column" elevation="0">
                <v-card-item>
                    <template v-slot:prepend>
                         <v-avatar color="primary" variant="tonal" class="glass-effect rounded-lg">
                            <v-icon icon="mdi-whatsapp"></v-icon>
                        </v-avatar>
                    </template>
                    <template v-slot:append>
                        <v-btn icon="mdi-delete" variant="text" size="small" color="error" @click="deleteInstance(inst.id)"></v-btn>
                    </template>
                    <v-card-title class="font-weight-bold">{{ inst.name }}</v-card-title>
                    <v-card-subtitle class="mt-1">
                        <v-chip size="x-small" :color="getStatusColor(inst.status)" class="text-uppercase font-weight-bold" label variant="flat">
                            <v-icon start size="x-small" icon="mdi-circle-medium"></v-icon>
                            {{ inst.status }}
                        </v-chip>
                    </v-card-subtitle>
                </v-card-item>

                <v-card-text class="flex-grow-1">
                    <div v-if="inst.user" class="d-flex align-center mt-4 pa-3 glass-effect rounded-lg">
                         <v-icon size="small" class="mr-2" color="success">mdi-account-check</v-icon>
                         <div>
                            <div class="text-body-2 font-weight-bold">{{ inst.user.name }}</div>
                            <div class="text-caption text-medium-emphasis">{{ inst.user.id }}</div>
                         </div>
                    </div>
                    <div v-else class="text-caption text-medium-emphasis mt-4 pa-3 text-center border-dashed rounded-lg">
                        Session Disconnected
                    </div>
                </v-card-text>

                <v-card-actions class="justify-end px-4 pb-4">
                    <v-btn 
                        v-if="inst.status !== 'connected'" 
                        variant="flat" 
                        color="success" 
                        class="shadow-button"
                        @click="startInstance(inst.id)"
                    >
                        Start Session
                    </v-btn>

                    <!-- Add Reset Button for Disconnected/Stuck states -->
                    <v-btn
                         v-if="inst.status === 'disconnected'"
                         variant="text"
                         color="warning"
                         size="small"
                         @click="stopInstance(inst.id)"
                    >
                        Reset
                    </v-btn>
                    
                    <v-btn 
                        v-if="inst.status === 'connecting' && inst.qr" 
                        variant="outlined" 
                        color="info"
                        class="glass-effect"
                        prepend-icon="mdi-qrcode"
                        @click="showQr(inst.qr, inst.name)"
                    >
                        Scan QR
                    </v-btn>

                    <v-btn 
                         v-if="inst.status === 'connected'"
                         variant="tonal" 
                         color="error" 
                         @click="stopInstance(inst.id)"
                    >
                        Logout
                    </v-btn>
                </v-card-actions>
            </v-card>
        </v-col>
    </v-row>

    <!-- QR Dialog -->
    <v-dialog v-model="qrDialog" width="auto">
        <v-card>
            <v-card-title class="text-center">Scan QR for {{ selectedName }}</v-card-title>
            <v-card-text class="text-center pa-4">
                <img :src="selectedQr" alt="QR Code" style="width: 256px; height: 256px;" />
            </v-card-text>
            <v-card-actions>
                <v-btn color="primary" block @click="qrDialog = false">Close</v-btn>
            </v-card-actions>
        </v-card>
    </v-dialog>

    <!-- Create Dialog -->
    <v-dialog v-model="createDialog" max-width="400">
        <v-card>
            <v-card-title>Add New Instance</v-card-title>
            <v-card-text>
                <v-text-field v-model="newInstanceName" label="Instance Name" variant="outlined" autofocus @keyup.enter="createInstance"></v-text-field>
            </v-card-text>
            <v-card-actions>
                <v-spacer></v-spacer>
                <v-btn @click="createDialog = false">Cancel</v-btn>
                <v-btn color="primary" @click="createInstance">Create</v-btn>
            </v-card-actions>
        </v-card>
    </v-dialog>

  </v-container>
</template>
