// src/ui/src/pages/Documentation.vue
<script setup lang="ts">
import { ref } from 'vue';

const tab = ref('curl');
const host = window.location.origin;

const endpoints = [
    {
        method: 'POST',
        url: '/api/wa/send/text/:instance_id',
        title: 'Send Text Message',
        desc: 'Send a plain text message to a specific phone number.',
        body: { to: '1234567890', message: 'Hello from API!' },
        code: {
            curl: `curl -X POST ${host}/api/wa/send/text/1 \\
  -H "Authorization: Bearer YOUR_TOKEN" \\
  -H "Content-Type: application/json" \\
  -d '{"to": "1234567890", "message": "Hello World"}'`,
            node: `const response = await fetch('${host}/api/wa/send/text/1', {
    method: 'POST',
    headers: {
        'Authorization': 'Bearer YOUR_TOKEN',
        'Content-Type': 'application/json'
    },
    body: JSON.stringify({
        to: '1234567890',
        message: 'Hello World'
    })
});
const data = await response.json();`,
            php: `$ch = curl_init();
curl_setopt($ch, CURLOPT_URL, "${host}/api/wa/send/text/1");
curl_setopt($ch, CURLOPT_POST, 1);
curl_setopt($ch, CURLOPT_HTTPHEADER, [
    "Authorization: Bearer YOUR_TOKEN",
    "Content-Type: application/json"
]);
curl_setopt($ch, CURLOPT_POSTFIELDS, json_encode([
    "to" => "1234567890",
    "message" => "Hello World"
]));
curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
$response = curl_exec($ch);
curl_close($ch);`,
            vb: `Dim client As New HttpClient()
client.DefaultRequestHeaders.Add("Authorization", "Bearer YOUR_TOKEN")

Dim json As String = "{""to"": ""1234567890"", ""message"": ""Hello World""}"
Dim content As New StringContent(json, Encoding.UTF8, "application/json")

Dim response = Await client.PostAsync("${host}/api/wa/send/text/1", content)
Dim result = Await response.Content.ReadAsStringAsync()`
        }
    },
    {
        method: 'POST',
        url: '/api/wa/send/image/:instance_id',
        title: 'Send Media / Image',
        desc: 'Send an image with an optional caption.',
        body: { to: '1234567890', url: 'https://example.com/image.png', caption: 'Check this out' },
        code: {
            curl: `curl -X POST ${host}/api/wa/send/image/1 \\
  -H "Authorization: Bearer YOUR_TOKEN" \\
  -H "Content-Type: application/json" \\
  -d '{"to": "1234567890", "url": "https://example.com/img.png", "caption": "Hi"}'`,
            node: `// using fetch
// ... same headers ...
body: JSON.stringify({
    to: '1234567890',
    url: 'https://example.com/image.png',
    caption: 'Cool Image'
})`,
            php: `// ... same setup ...
curl_setopt($ch, CURLOPT_POSTFIELDS, json_encode([
    "to" => "1234567890",
    "url" => "https://example.com/image.png",
    "caption" => "Cool Image"
]));`,
            vb: `Dim json As String = "{""to"": ""..."", ""url"": ""..."", ""caption"": ""...""}"
' ... send request ...`
        }
    },
    {
        method: 'POST',
        url: '/api/wa/send/video/:instance_id',
        title: 'Send Video',
        desc: 'Send a video (MP4) with optional caption and GIF playback mode.',
        body: { to: '1234567890', url: 'https://example.com/video.mp4', caption: 'Watch this', gifPlayback: false },
        code: {
            curl: `curl -X POST ${host}/api/wa/send/video/1 \\
  -H "Authorization: Bearer YOUR_TOKEN" \\
  -H "Content-Type: application/json" \\
  -d '{"to": "1234567890", "url": "https://example.com/video.mp4", "caption": "Watch this"}'`,
            node: `// Body
{
    to: '1234567890',
    url: 'https://example.com/video.mp4',
    caption: 'Watch this',
    gifPlayback: false
}`
        }
    },
    {
        method: 'POST',
        url: '/api/wa/send/audio/:instance_id',
        title: 'Send Audio (Voice)',
        desc: 'Send an audio file or voice note (PTT).',
        body: { to: '1234567890', url: 'https://example.com/audio.mp3', ptt: true },
        code: {
            curl: `curl -X POST ${host}/api/wa/send/audio/1 \\
  -H "Authorization: Bearer YOUR_TOKEN" \\
  -H "Content-Type: application/json" \\
  -d '{"to": "1234567890", "url": "https://example.com/audio.mp3", "ptt": true}'`,
            node: `// Body
{
    to: '1234567890',
    url: 'https://example.com/audio.mp3',
    ptt: true // true = Voice Note, false = Audio File
}`
        }
    },
    {
        method: 'POST',
        url: '/api/wa/send/document/:instance_id',
        title: 'Send Document',
        desc: 'Send a file/document.',
        body: { to: '1234567890', url: 'https://example.com/file.pdf', filename: 'invoice.pdf' },
        code: {
            curl: `curl -X POST ${host}/api/wa/send/video/1 \\
  -H "Authorization: Bearer YOUR_TOKEN" \\
  -H "Content-Type: application/json" \\
  -d '{"to": "1234567890", "url": "https://example.com/file.pdf", "filename": "invoice.pdf"}'`,
            node: `// Body
{
    to: '1234567890',
    url: 'https://example.com/file.pdf',
    filename: 'invoice.pdf'
}`
        }
    },
    {
        method: 'POST',
        url: '/api/wa/send/location/:instance_id',
        title: 'Send Location',
        desc: 'Send a geo-location.',
        body: { to: '1234567890', latitude: 24.123, longitude: 55.123, address: 'Burj Khalifa' },
        code: {
            curl: `curl -X POST ${host}/api/wa/send/location/1 \\
  -H "Authorization: Bearer YOUR_TOKEN" \\
  -H "Content-Type: application/json" \\
  -d '{"to": "1234567890", "latitude": 24.123, "longitude": 55.123, "address": "Burj Khalifa"}'`,
            node: `// Body
{
    to: '1234567890',
    latitude: 24.123,
    longitude: 55.123,
    address: 'My Location'
}`
        }
    }
];
</script>

<template>
  <v-container>
    <div class="mb-6 d-flex align-center justify-space-between flex-wrap gap-4">
        <div>
            <h1 class="text-h3 font-weight-bold text-primary mb-2">API Documentation</h1>
            <p class="text-subtitle-1 text-medium-emphasis">
                Integrate WhatsApp automation directly into your external applications.
            </p>
        </div>
        <v-btn
            color="orange"
            prepend-icon="mdi-download"
            href="/xiw-bot.postman_collection.json"
            download="xiw-bot.postman_collection.json"
            target="_blank" 
            variant="tonal"
        >
            Download Postman Collection
        </v-btn>
    </div>

    <!-- Workflow Section -->
    <v-card class="mb-8" border>
        <v-card-title class="font-weight-bold">
            <v-icon color="primary" class="mr-2">mdi-sitemap</v-icon>
            Integration Workflow
        </v-card-title>
        <v-card-text>
            <v-timeline density="compact" align="start">
                <v-timeline-item dot-color="primary" size="x-small">
                    <div class="mb-2"><strong>1. Generate API Token</strong></div>
                    <div class="text-caption">
                        Go to the <strong>Users</strong> section in the dashboard and generate a scoped API Token for your application.
                        Each token is linked to specific permissions.
                    </div>
                </v-timeline-item>

                <v-timeline-item dot-color="secondary" size="x-small">
                    <div class="mb-2"><strong>2. Authenticate Requests</strong></div>
                    <div class="text-caption">
                        Include the token in the HTTP Header of every request:
                        <v-chip size="small" class="mt-1 font-weight-bold" label>Authorization: Bearer YOUR_TOKEN</v-chip>
                    </div>
                </v-timeline-item>

                <v-timeline-item dot-color="success" size="x-small">
                    <div class="mb-2"><strong>3. Send Messages</strong></div>
                    <div class="text-caption">
                        Use the <code>POST</code> endpoints exposed below to send text or media messages.
                        Ensure you use the correct <code>instance_id</code> assigned to your user account.
                    </div>
                </v-timeline-item>
            </v-timeline>
        </v-card-text>
    </v-card>

    <v-divider class="mb-8"></v-divider>

    <!-- Endpoints -->
    <div v-for="(ep, i) in endpoints" :key="i" class="mb-10">
        <div class="d-flex align-center mb-4">
            <v-chip :color="ep.method === 'GET' ? 'blue' : 'green'" class="mr-3 font-weight-bold" label>
                {{ ep.method }}
            </v-chip>
            <h2 class="text-h5 font-weight-medium">{{ ep.url }}</h2>
        </div>

        <p class="text-body-1 mb-4">{{ ep.desc }}</p>

        <v-card variant="flat" border class="bg-surface">
            <v-tabs v-model="tab" bg-color="surface-variant" density="compact">
                <v-tab value="curl">cURL</v-tab>
                <v-tab value="node">Node.js</v-tab>
                <v-tab value="php">PHP</v-tab>
                <v-tab value="vb">VB.NET</v-tab>
            </v-tabs>

            <v-card-text class="pa-0">
                <v-window v-model="tab">
                    <v-window-item value="curl">
                        <v-code class="d-block pa-4 bg-background" style="white-space: pre-wrap; font-family: monospace;">
                            {{ ep.code.curl }}
                        </v-code>
                    </v-window-item>
                    <v-window-item value="node">
                        <v-code class="d-block pa-4 bg-background" style="white-space: pre-wrap; font-family: monospace;">
                            {{ ep.code.node }}
                        </v-code>
                    </v-window-item>
                    <v-window-item value="php">
                        <v-code class="d-block pa-4 bg-background" style="white-space: pre-wrap; font-family: monospace;">
                            {{ ep.code.php }}
                        </v-code>
                    </v-window-item>
                    <v-window-item value="vb">
                        <v-code class="d-block pa-4 bg-background" style="white-space: pre-wrap; font-family: monospace;">
                            {{ ep.code.vb }}
                        </v-code>
                    </v-window-item>
                </v-window>
            </v-card-text>
        </v-card>
    </div>

    <v-alert type="info" variant="tonal" class="mt-8">
        <strong>Agent Access</strong><br>
        Agents cannot login to the dashboard. They must use the <strong>Static Token</strong> generated by the Admin to access the API.
    </v-alert>

  </v-container>
</template>

<style scoped>
pre { margin: 0; }
</style>

// src/ui/src/pages/Documentation.tsx
import React, { useEffect, useState } from 'react';
import { Download, ArrowLeft, Terminal, Shield, Key, AlertTriangle } from 'lucide-react';
import { useNavigate } from 'react-router-dom';

const Documentation = () => {
    const navigate = useNavigate();
    const [baseUrl, setBaseUrl] = useState('');

    useEffect(() => {
        setBaseUrl(window.location.origin);
    }, []);

    const CodeBlock = ({ children, title }: { children: React.ReactNode, title?: string }) => (
        <div style={{ marginTop: '0.5rem', marginBottom: '1rem' }}>
            {title && <div style={{ fontSize: '0.75rem', color: 'var(--text-sub)', marginBottom: '0.25rem' }}>{title}</div>}
            <pre style={{
                background: '#16161a',
                padding: '1rem',
                borderRadius: '8px',
                overflowX: 'auto',
                border: '1px solid rgba(255,255,255,0.1)',
                margin: 0
            }}>
                <code style={{ fontFamily: 'monospace', fontSize: '0.875rem', color: '#a8b1ff' }}>
                    {children}
                </code>
            </pre>
        </div>
    );

    const Endpoint = ({ method, url, desc }: { method: string, url: string, desc: string }) => (
        <div style={{ marginBottom: '1.5rem', padding: '1rem', background: 'rgba(255,255,255,0.03)', borderRadius: '8px' }}>
            <div style={{ display: 'flex', alignItems: 'center', gap: '0.75rem', marginBottom: '0.5rem', flexWrap: 'wrap' }}>
                <span style={{
                    fontWeight: 'bold',
                    color: method === 'GET' ? 'var(--success)' : method === 'POST' ? 'var(--accent)' : 'var(--error)',
                    background: method === 'GET' ? 'rgba(44, 182, 125, 0.1)' : method === 'POST' ? 'rgba(127, 90, 240, 0.1)' : 'rgba(239, 69, 101, 0.1)',
                    padding: '0.25rem 0.5rem',
                    borderRadius: '4px',
                    fontSize: '0.75rem'
                }}>{method}</span>
                <code style={{ fontSize: '0.9rem' }}>{baseUrl}{url}</code>
            </div>
            <p style={{ color: 'var(--text-sub)', fontSize: '0.875rem', margin: 0 }}>{desc}</p>
        </div>
    );

    return (
        <div className="fade-in" style={{ padding: '2rem', maxWidth: '1000px', margin: '0 auto', width: '100%' }}>
            {/* Header */}
            <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '3rem' }}>
                <div style={{ display: 'flex', alignItems: 'center', gap: '1rem' }}>
                    <button onClick={() => navigate('/dashboard')} style={{ background: 'transparent', color: 'var(--text-sub)', padding: 0 }}>
                        <ArrowLeft size={24} />
                    </button>
                    <div>
                        <h1 style={{ fontSize: '2rem', fontWeight: 'bold' }}>API Documentation</h1>
                        <p style={{ color: 'var(--text-sub)' }}>Integrate XiW Bot into your applications</p>
                    </div>
                </div>
                <a href="/xiw-bot.postman_collection.json" download className="btn-primary" style={{ display: 'flex', alignItems: 'center', gap: '0.5rem', textDecoration: 'none' }}>
                    <Download size={18} />
                    Download Postman Collection
                </a>
            </div>

            <div style={{ display: 'grid', gridTemplateColumns: '1fr 300px', gap: '2rem' }}>

                {/* Main Content */}
                <div style={{ display: 'flex', flexDirection: 'column', gap: '3rem' }}>

                    {/* Auth Section */}
                    <section>
                        <h2 style={{ display: 'flex', alignItems: 'center', gap: '0.75rem', fontSize: '1.5rem', marginBottom: '1.5rem', borderBottom: '1px solid rgba(255,255,255,0.1)', paddingBottom: '0.5rem' }}>
                            <Shield size={24} color="var(--accent)" />
                            Authentication
                        </h2>
                        <p style={{ color: 'var(--text-sub)', lineHeight: '1.6' }}>
                            Your API requests must be authenticated using a <strong>Bearer Token</strong>. You can generate a <strong>Scoped API Token</strong> from the Dashboard. These tokens start with <code>xiw_</code>.
                        </p>
                        <div style={{ padding: '1rem', background: 'rgba(239, 69, 101, 0.1)', border: '1px solid rgba(239, 69, 101, 0.2)', borderRadius: '8px', marginBottom: '1rem' }}>
                            <div style={{ display: 'flex', gap: '0.5rem', color: 'var(--error)', fontWeight: 'bold', marginBottom: '0.5rem' }}>
                                <AlertTriangle size={18} /> Important
                            </div>
                            <p style={{ fontSize: '0.875rem', color: 'var(--text-sub)', margin: 0 }}>
                                API Tokens are <strong>scoped</strong>. They can only send messages from the WhatsApp Accounts they were explicitly assigned to during generation. They <strong>cannot</strong> create or delete accounts.
                            </p>
                        </div>
                        <CodeBlock title="Header Example">
                            Authorization: Bearer xiw_123abc...
                        </CodeBlock>
                    </section>

                    {/* Endpoints Section */}
                    <section>
                        <h2 style={{ display: 'flex', alignItems: 'center', gap: '0.75rem', fontSize: '1.5rem', marginBottom: '1.5rem', borderBottom: '1px solid rgba(255,255,255,0.1)', paddingBottom: '0.5rem' }}>
                            <Terminal size={24} color="var(--success)" />
                            Messaging Endpoints
                        </h2>
                        <p style={{ color: 'var(--text-sub)', marginBottom: '1.5rem' }}>
                            Replace <code>:id</code> with the ID of your WhatsApp Instance (e.g. <code>1</code>).
                        </p>

                        <Endpoint method="POST" url="/api/wa/send/text/:id" desc="Send a text message." />
                        <CodeBlock title="cURL Example">
                            {`curl --location '${baseUrl}/api/wa/send/text/1' \\
--header 'Content-Type: application/json' \\
--header 'Authorization: Bearer xiw_YOUR_TOKEN' \\
--data '{
    "to": "1234567890",
    "message": "Hello from your bot!"
}'`}
                        </CodeBlock>

                        <Endpoint method="POST" url="/api/wa/send/image/:id" desc="Send an image from a URL." />
                        <CodeBlock title="Payload">
                            {`{
  "to": "1234567890",
  "url": "https://example.com/image.png",
  "caption": "Optional caption"
}`}
                        </CodeBlock>

                        <Endpoint method="POST" url="/api/wa/send/video/:id" desc="Send a video (mp4)." />
                        <CodeBlock title="Payload">
                            {`{
  "to": "1234567890",
  "url": "https://example.com/video.mp4",
  "caption": "Check this video"
}`}
                        </CodeBlock>

                        <Endpoint method="POST" url="/api/wa/send/document/:id" desc="Send a document (pdf, docx, etc)." />
                        <CodeBlock title="Payload">
                            {`{
  "to": "1234567890",
  "url": "https://example.com/invoice.pdf",
  "filename": "invoice_123.pdf", 
  "caption": "Here is your invoice"
}`}
                        </CodeBlock>

                        <h2 style={{ fontSize: '1.5rem', marginTop: '3rem', marginBottom: '1.5rem', borderBottom: '1px solid rgba(255,255,255,0.1)', paddingBottom: '0.5rem' }}>
                            Instance Management
                        </h2>

                        <Endpoint method="POST" url="/api/wa/start/:id" desc="Start the WhatsApp session." />

                        <Endpoint method="GET" url="/api/wa/status" desc="Get status of all allowed instances (Admin: All, Agent: Assigned)." />
                        <CodeBlock title="Response (List)">
                            {`{
  "instances": [
    {
      "id": 1,
      "name": "Support Bot",
      "status": "connected",
      "qr": null,
      "user": { "name": "My Business", "id": "12345@s.whatsapp.net" }
    }
  ]
}`}
                        </CodeBlock>

                        <Endpoint method="GET" url="/api/wa/status/:id" desc="Get status of a specific instance." />
                        <CodeBlock title="Response (Single)">
                            {`{
  "status": "connected", 
  "qr": null,
  "user": { ... }
}`}
                        </CodeBlock>

                        <h2 style={{ fontSize: '1.5rem', marginTop: '3rem', marginBottom: '1.5rem', borderBottom: '1px solid rgba(255,255,255,0.1)', paddingBottom: '0.5rem' }}>
                            Token Management (Admin)
                        </h2>

                        <Endpoint method="POST" url="/api/tokens" desc="Generate a new Scoped API Token. (Admin Only)" />
                        <CodeBlock title="Payload">
                            {`{
  "name": "Production App",
  "userId": 2, // Agent ID to assign to
  "instanceIds": [1, 3] // Array of allowed Instance IDs
}`}
                        </CodeBlock>
                    </section>

                </div>

                {/* Quick Start / Side */}
                <div style={{ background: 'rgba(255,255,255,0.02)', padding: '1.5rem', borderRadius: '12px', height: 'fit-content', position: 'sticky', top: '2rem' }}>
                    <h3 style={{ fontSize: '1.25rem', marginBottom: '1rem', display: 'flex', alignItems: 'center', gap: '0.5rem' }}>
                        <Key size={20} /> Quick Start
                    </h3>
                    <ol style={{ paddingLeft: '1.2rem', color: 'var(--text-sub)', lineHeight: '1.6', display: 'flex', flexDirection: 'column', gap: '0.5rem' }}>
                        <li>Go to <strong>Dashboard</strong>.</li>
                        <li>Scroll to <strong>API Tokens</strong>.</li>
                        <li>Select an User and Instances.</li>
                        <li>Generate & Copy the token.</li>
                        <li>Use the live URL below:</li>
                    </ol>
                    <div style={{ background: 'rgba(0,0,0,0.3)', padding: '0.5rem', borderRadius: '4px', fontSize: '0.75rem', wordBreak: 'break-all', marginTop: '0.5rem', color: 'var(--accent)' }}>
                        {baseUrl || 'Loading...'}
                    </div>
                </div>

            </div>
        </div>
    );
};

export default Documentation;
