// src/ui/src/pages/Login.vue
<script setup lang="ts">
import { ref } from 'vue';
import { useRouter } from 'vue-router';

const username = ref('');
const password = ref('');
const loading = ref(false);
const error = ref('');
const showPass = ref(false);
const router = useRouter();

const handleLogin = async () => {
    loading.value = true;
    error.value = '';
    try {
        const res = await fetch('/api/auth/login', {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify({ username: username.value, password: password.value }),
        });

        const data = await res.json();
        if (!res.ok) throw new Error(data.error || 'Login failed');

        localStorage.setItem('token', data.token);
        window.dispatchEvent(new Event('auth-change'));
        router.push('/dashboard');
    } catch (e: any) {
        error.value = e.message;
    } finally {
        loading.value = false;
    }
};
</script>

<template>
  <v-container class="fill-height justify-center">
    <v-card width="400" class="pa-4 glass-panel" elevation="8" rounded="lg">
      <v-card-title class="text-h4 font-weight-bold text-center text-primary mb-4">
        XiW Bot
      </v-card-title>
      <v-card-subtitle class="text-center mb-6">
        Enterprise WhatsApp Automation
      </v-card-subtitle>

      <v-card-text>
        <v-text-field
            v-model="username"
            label="Username"
            prepend-inner-icon="mdi-account"
            variant="outlined"
            bg-color="surface"
        ></v-text-field>

        <v-text-field
            v-model="password"
            :type="showPass ? 'text' : 'password'"
            label="Password"
            prepend-inner-icon="mdi-lock"
            :append-inner-icon="showPass ? 'mdi-eye' : 'mdi-eye-off'"
            @click:append-inner="showPass = !showPass"
            variant="outlined"
            bg-color="surface"
            @keyup.enter="handleLogin"
        ></v-text-field>

        <v-alert v-if="error" type="error" variant="tonal" class="mb-4" density="compact">
            {{ error }}
        </v-alert>

        <v-btn
            block
            color="primary"
            size="large"
            :loading="loading"
            @click="handleLogin"
            class="mt-2"
        >
            Login
        </v-btn>
      </v-card-text>
    </v-card>
  </v-container>
</template>

<style scoped>
.glass-panel {
    background: rgba(22, 22, 26, 0.9) !important;
    backdrop-filter: blur(10px);
}
</style>

// src/ui/src/pages/Login.tsx
import React, { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { Shield, Lock, User } from 'lucide-react';

const Login = () => {
    const [username, setUsername] = useState('');
    const [password, setPassword] = useState('');
    const [loading, setLoading] = useState(false);
    const [error, setError] = useState('');
    const navigate = useNavigate();

    const handleLogin = async (e: React.FormEvent) => {
        e.preventDefault();
        setLoading(true);
        setError('');

        try {
            const res = await fetch('/api/auth/login', {
                method: 'POST',
                headers: { 'Content-Type': 'application/json' },
                body: JSON.stringify({ username, password }),
            });

            const data = await res.json();

            if (!res.ok) {
                throw new Error(data.error || 'Login failed');
            }

            localStorage.setItem('token', data.token);
            // Dispatch event to update navbar immediately
            window.dispatchEvent(new Event('auth-change'));
            navigate('/dashboard');
        } catch (err: any) {
            setError(err.message);
        } finally {
            setLoading(false);
        }
    };

    return (
        <div className="hero min-h-screen bg-base-200">
            <div className="hero-content flex-col lg:flex-row-reverse">
                <div className="text-center lg:text-left text-white max-w-md">
                    <h1 className="text-5xl font-bold bg-gradient-to-r from-primary to-secondary bg-clip-text text-transparent">XiW Bot</h1>
                    <p className="py-6 text-base-content/80">
                        Enterprise WhatsApp Automation. Manage multiple instances, agents, and secure messaging channels from a single dashboard.
                    </p>
                </div>
                <div className="card shrink-0 w-full max-w-sm shadow-2xl bg-base-100">
                    <form className="card-body" onSubmit={handleLogin}>
                        <div className="form-control">
                            <label className="label">
                                <span className="label-text">Username</span>
                            </label>
                            <label className="input input-bordered flex items-center gap-2">
                                <User className="w-4 h-4 opacity-70" />
                                <input
                                    type="text"
                                    className="grow"
                                    placeholder="admin"
                                    value={username}
                                    onChange={(e) => setUsername(e.target.value)}
                                />
                            </label>
                        </div>
                        <div className="form-control">
                            <label className="label">
                                <span className="label-text">Password</span>
                            </label>
                            <label className="input input-bordered flex items-center gap-2">
                                <Lock className="w-4 h-4 opacity-70" />
                                <input
                                    type="password"
                                    className="grow"
                                    value={password}
                                    onChange={(e) => setPassword(e.target.value)}
                                />
                            </label>
                            {/* <label className="label">
                                <a href="#" className="label-text-alt link link-hover">Forgot password?</a>
                            </label> */}
                        </div>
                        {error && (
                            <div role="alert" className="alert alert-error text-sm py-2">
                                <Shield className="w-4 h-4" />
                                <span>{error}</span>
                            </div>
                        )}
                        <div className="form-control mt-6">
                            <button className="btn btn-primary" disabled={loading}>
                                {loading ? <span className="loading loading-spinner"></span> : 'Login'}
                            </button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    );
};

export default Login;
